/* libusb-win32_version.h ++ auto-generated
*/
#ifndef __LIBUSB_WIN32_VERSION_H
#define __LIBUSB_WIN32_VERSION_H

#define __DEFTOSTR(x) #x
#define  _DEFTOSTR(x) __DEFTOSTR(x)

#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_MICRO 2
#define VERSION_NANO  0
#define VERSION_DATE 10/02/2010

#define VERSION VERSION_MAJOR.VERSION_MINOR.VERSION_MICRO.VERSION_NANO
#define RC_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_MICRO,VERSION_NANO

#endif
