/*
 * INF templates for WinUSB/libusb automated driver installation
 * Copyright (c) 2010 Pete Batard <pbatard@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */
#pragma once

const char winusb_inf[] =
	"ServiceDesc = \"WinUSB Driver\"\n"
	"DiskName = \"libusb (WinUSB) Device Install Disk\"\n"
	"ClassName = \"libusb (WinUSB) devices\"\n"
	"\n"
	"[Version]\n"
	"DriverVer = %Date%,1\n"
	"Signature = \"$Windows NT$\"\n"
	"Class = %ClassName%\n"
	"ClassGuid = {78a1c341-4539-11d3-b88d-00c04fad5171}\n"
	"Provider = \"libusb.org\"\n"
	"CatalogFile = %CatName%\n"
	"\n"
	"[ClassInstall32]\n"
	"Addreg = WinUSBDeviceClassReg\n"
	"\n"
	"[WinUSBDeviceClassReg]\n"
	"HKR,,,0,%ClassName%\n"
	"HKR,,Icon,,-20\n"
	"\n"
	"[Manufacturer]\n"
	"%VendorName% = libusbDevice_WinUSB,NTx86,NTamd64,NTia64\n"
	"\n"
	"[libusbDevice_WinUSB.NTx86]\n"
	"%DeviceName% = USB_Install, USB\\%DeviceID%\n"
	"\n"
	"[libusbDevice_WinUSB.NTamd64]\n"
	"%DeviceName% = USB_Install, USB\\%DeviceID%\n"
	"\n"
	"[libusbDevice_WinUSB.NTia64]\n"
	"%DeviceName% = USB_Install, USB\\%DeviceID%\n"
	"\n"
	"[USB_Install]\n"
	"Include=winusb.inf\n"
	"Needs=WINUSB.NT\n"
	"\n"
	"[USB_Install.Services]\n"
	"Include=winusb.inf\n"
	"AddService=WinUSB,0x00000002,WinUSB_ServiceInstall\n"
	"\n"
	"[WinUSB_ServiceInstall]\n"
	"DisplayName     = %ServiceDesc%\n"
	"ServiceType     = 1\n"
	"StartType       = 3\n"
	"ErrorControl    = 1\n"
	"ServiceBinary   = %12%\\WinUSB.sys\n"
	"\n"
	"[USB_Install.Wdf]\n"
	"KmdfService=WINUSB, WinUsb_Install\n"
	"\n"
	"[WinUSB_Install]\n"
	"KmdfLibraryVersion=1.9\n"
	"\n"
	"[USB_Install.HW]\n"
	"AddReg=Dev_AddReg\n"
	"\n"
	"[Dev_AddReg]\n"
	"HKR,,DeviceInterfaceGUIDs,0x10000,%DeviceGUID%\n"
	"\n"
	"[USB_Install.CoInstallers]\n"
	"AddReg=CoInstallers_AddReg\n"
	"CopyFiles=CoInstallers_CopyFiles\n"
	"\n"
	"[CoInstallers_AddReg]\n"
	"HKR,,CoInstallers32,0x00010000,\"WdfCoInstaller01009.dll,WdfCoInstaller\",\"WinUSBCoInstaller2.dll\"\n"
	"\n"
	"[CoInstallers_CopyFiles]\n"
	"WinUSBCoInstaller2.dll\n"
	"WdfCoInstaller01009.dll\n"
	"\n"
	"[DestinationDirs]\n"
	"CoInstallers_CopyFiles=11\n"
	"\n"
	"[SourceDisksNames]\n"
	"1 = %DiskName%\n"
	"\n"
	"[SourceDisksFiles.x86]\n"
	"WinUSBCoInstaller2.dll=1,x86\n"
	"WdfCoInstaller01009.dll=1,x86\n"
	"\n"
	"[SourceDisksFiles.amd64]\n"
	"WinUSBCoInstaller2.dll=1,amd64\n"
	"WdfCoInstaller01009.dll=1,amd64\n"
	"\n"
	"[SourceDisksFiles.ia64]\n"
	"WinUSBCoInstaller2.dll=1,ia64\n"
	"WdfCoInstaller01009.dll=1,ia64\n";

const char libusb_inf[] =
	"ServiceDesc = \"libusb-win32 Kernel Driver\"\n"
	"DiskName = \"libusb-win32 Device Install Disk\"\n"
	"ClassName = \"libusb-win32 devices\"\n"
	"\n"
	"[Version]\n"
	"Signature = \"$Windows NT$\"\n"
	"Class     = %ClassName%\n"
	"ClassGuid = {EB781AAF-9C70-4523-A5DF-642A87ECA567}\n"
	"Provider  = \"libusb-win32\"\n"
	"CatalogFile = %CatName%\n"
	"DriverVer = %Date%,1\n"
	"\n"
	"[ClassInstall32]\n"
	"Addreg=libusb_class_install_add_reg\n"
	"\n"
	"[libusb_class_install_add_reg]\n"
	"HKR,,,0,%ClassName%\n"
	"HKR,,Icon,,-20\n"
	"\n"
	"[Manufacturer]\n"
	"%VendorName%=Devices, NT, NTAMD64, NTIA64\n"
	"\n"
	";--------------------------------------------------------------------------\n"
	"; libusb-win32 files\n"
	";--------------------------------------------------------------------------\n"
	"\n"
	"[SourceDisksNames]\n"
	"1 = %DiskName%\n"
	"\n"
	"[SourceDisksFiles.x86]\n"
	"libusb0.sys = 1,x86\n"
	"libusb0_x86.dll = 1,x86\n"
	"\n"
	"[SourceDisksFiles.amd64]\n"
	"libusb0.sys = 1,amd64\n"
	"libusb0.dll = 1,amd64\n"
	"libusb0_x86.dll = 1,x86\n"
	"\n"
	"[SourceDisksFiles.ia64]\n"
	"libusb0.sys = 1,ia64\n"
	"libusb0.dll = 1,ia64\n"
	"libusb0_x86.dll = 1,x86\n"
	"\n"
	"[DestinationDirs]\n"
	"libusb_files_sys = 10,system32\\drivers\n"
	"libusb_files_dll = 10,system32\n"
	"libusb_files_dll_wow64 = 10,syswow64\n"
	"libusb_files_dll_x86 = 10,system32\n"
	"\n"
	"[libusb_files_sys]\n"
	"libusb0.sys\n"
	"\n"
	"[libusb_files_dll]\n"
	"libusb0.dll\n"
	"\n"
	"[libusb_files_dll_x86]\n"
	"libusb0.dll, libusb0_x86.dll\n"
	"\n"
	"[libusb_files_dll_wow64]\n"
	"libusb0.dll, libusb0_x86.dll\n"
	"\n"
	";--------------------------------------------------------------------------\n"
	"; libusb-win32 device driver\n"
	";--------------------------------------------------------------------------\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NT]\n"
	"CopyFiles = libusb_files_sys, libusb_files_dll_x86\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTAMD64]\n"
	"CopyFiles = libusb_files_sys, libusb_files_dll, libusb_files_dll_wow64\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTIA64]\n"
	"CopyFiles = libusb_files_sys, libusb_files_dll, libusb_files_dll_wow64\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NT.HW]\n"
	"DelReg = libusb_del_reg_hw\n"
	"AddReg = libusb_add_reg_hw\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTAMD64.HW]\n"
	"DelReg = libusb_del_reg_hw\n"
	"AddReg = libusb_add_reg_hw\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTIA64.HW]\n"
	"DelReg = libusb_del_reg_hw\n"
	"AddReg = libusb_add_reg_hw\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NT.Services]\n"
	"AddService = libusb0, 0x00000002, libusb_add_service\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTAMD64.Services]\n"
	"AddService = libusb0, 0x00000002, libusb_add_service\n"
	"\n"
	"[LIBUSB_WIN32_DEV.NTIA64.Services]\n"
	"AddService = libusb0, 0x00000002, libusb_add_service\n"
	"\n"
	"; Older versions of this .inf file installed filter drivers. They are not\n"
	"; needed any more and must be removed\n"
	"[libusb_del_reg_hw]\n"
	"HKR,,LowerFilters\n"
	"HKR,,UpperFilters\n"
	"\n"
	"; libusb-win32 device properties\n"
	"[libusb_add_reg_hw]\n"
	"HKR,,SurpriseRemovalOK, 0x00010001, 1\n"
	"\n"
	"; (Optional) the usb configuration value to select when this device\n"
	"; is started.  If this key does not exist the first config is selected.\n"
	";HKR,,InitialConfigValue,0x00010001,<your config value>\n"
	"\n"
	";--------------------------------------------------------------------------\n"
	"; libusb-win32 service\n"
	";--------------------------------------------------------------------------\n"
	"\n"
	"[libusb_add_service]\n"
	"DisplayName    = %ServiceDesc%\n"
	"ServiceType    = 1\n"
	"StartType      = 3\n"
	"ErrorControl   = 0\n"
	"ServiceBinary  = %12%\\libusb0.sys\n"
	"\n"
	";--------------------------------------------------------------------------\n"
	"; LIBUSB_WIN32\n"
	";--------------------------------------------------------------------------\n"
	"\n"
	"; Hardware IDs in a 'Devices' section can be installed by libusb-win32\n"
	"; using usb_install_driver_np(), usb_install_driver_np_rundll(), or the\n"
	"; inf-wizard utility.\n"
	";\n"
	"[Devices]\n"
	"%DeviceName% = LIBUSB_WIN32_DEV, USB\\%DeviceID%\n"
	"\n"
	"[Devices.NT]\n"
	"%DeviceName% = LIBUSB_WIN32_DEV.NT, USB\\%DeviceID%\n"
	"\n"
	"[Devices.NTAMD64]\n"
	"%DeviceName% = LIBUSB_WIN32_DEV.NTAMD64, USB\\%DeviceID%\n"
	"\n"
	"[Devices.NTIA64]\n"
	"%DeviceName% = LIBUSB_WIN32_DEV.NTIA64, USB\\%DeviceID%\n"
	"\n";

const char* inf[2] = {winusb_inf, libusb_inf};
